site_name: ArXiv Daily Tracker
site_url: https://DieRingedesSaturn.github.io/arxiv_daily/
edit_uri: ""

theme:
  name: material
  language: zh
  palette:
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  features:
    - navigation.indexes
    - search.suggest

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink

nav:
  - 首页: index.md
  - arxiv 日报: posts/
  - ATel 简报: atels/

plugins:
  - search